R/SurfaceMap.R

Fix colon in filenames in SurfaceMap.

---

R/InteractiveCovariateMap.R
R/InteractiveMap.R

This:
```r
library(zoon)
work2 <- workflow(occurrence = CWBZimbabwe,
covariate = Bioclim(extent = c(28, 38, -25, -15),
res = 2.5),
process = NoProcess,
model = LogisticRegression,
output = list(InteractiveMap,
InteractiveCovariateMap(which = 2)))
```
Now gives something like this:
and this:
which is

Beefing up interactive maps

---

R/Bioclim.R
R/GBM.R
R/InteractiveCovariateMap.R
R/MaxEnt.R
man/Bioclim.Rd

ResponseCurve error & BioClim layers

closing some more issues

---

R/GBM.R
R/MachineLearn.R
R/MaxEnt.R
R/PrintMap.R
man/BiomodModel.Rd
man/GBM.Rd
man/LogisticRegression.Rd
man/MaxEnt.Rd
man/OptGRaF.Rd
man/QuickGRaF.Rd
man/RandomForest.Rd
man/mgcv.Rd
tests/test-MachineLearn.R

- Add MachineLearn module which accesses all the models in caret.
* This find which packages were used (you won't know before hand) and records it properly.
- Much improved PrintMap module. 
* Axes are still annoying me though.

Map and caret

---

R/Bioclim.R
R/PrintMap.R
tests/test-Bioclim.R
tests/test-PrintMap.R

Fix bugs in printmap
Add PrintMap tests
Add default extent to bioclim.
Add a bioclim test.

Pr map and caret

---

R/MachineLearn.R

Claim MachineLearn authorship.

---

R/Clean.R

Add a first go at a data cleaning module.

Zoon apps modules

---

R/LocalRaster.R

Added support for vectors of filenames, RasterLayer and RasterStack objects

added support for extra input types in module LocalRaster

---

R/Background.R

Background can now take a length 1 numeric for `bias` which then takes background points from within `bias` kilometres from presence points.

Update background module

---

R/Background.R
R/LocalOccurrenceData.R

*Can now deal with comma seperated or semicolon seperated data.
*Can deal with decimels using . or ,
*Uses `data.table` package as a fall back.
Closes #66

LocalOccurrenceData made more robust

---

R/LocalRaster.R

Added support for raster, rasterStack, and RasterBrick objects stored in the global environment

LocalRaster

---

R/LocalRaster.R

GetPackage is exported so needs :: not :::  .

Minor code cleanup.

---

R/InteractiveMap.R
man/PrintMap.Rd
tests/test-all.R

... and add in the PrintMap help doc

Fixes to Interactive Map

---

R/AirNCEP.R
R/AnophelesPlumbeus.R
R/Background.R
R/BiomodModel.R
R/Clean.R
R/Figshare.R
R/InteractiveCovariateMap.R
R/InteractiveMap.R
R/LocalOccurrenceData.R
R/MESSMask.R
R/MachineLearn.R
R/MaxEnt.R
R/NCEP.R
R/OneHundredBackground.R
R/PerformanceMeasures.R
R/PrintMap.R
R/RandomForest.R
R/SpOcc.R

- note that while GetPackage can take a vector I do not implement that here as it would break the cran version

All calls to GetPackage made 'quoted'

---

R/PrintMap.R
man/PrintMap.Rd

+ reformatting a little code & generating the documentation

making point plotting optional in PrintMap

---

R/Background.R
R/BackgroundAndCrossvalid.R
R/Crossvalidate.R
R/NoProcess.R
R/OneHundredBackground.R
R/OneThousandBackground.R

Currently Zoon will work with or without this attribute but I need to put it in now so that the vignette examples (which use the attribute) work

Add covCol attribute to process modules

---

R/Background.R
R/BackgroundAndCrossvalid.R
R/Crossvalidate.R
R/NoProcess.R
R/OneHundredBackground.R
R/OneThousandBackground.R

Reverts zoonproject/modules#84

Revert "Add covCol attribute to process modules"

---

R/ROCcurve.R
R/SeparatePA.R

First version of output module to produce ROC curve and module to show separation (in probability) of P/A groups.

First version of two output modules

---

R/AddRandomUniformPredictors.R
R/Background.R
R/BackgroundAndCrossvalid.R
R/Crossvalidate.R
R/LocalOccurrenceData.R
R/NaiveRandomRaster.R
R/OneHundredBackground.R
R/OneThousandBackground.R
R/PredictNewRasterMap.R
man/AddRandomUniformPredictors.Rd
tests/testthat.R
tests/testthat/testGenericTests.R

... and some other minor changes mainly linked to allowing other CRSs

Allows column names to pass on from LocalOccurreceData

---

R/Background.R
R/BackgroundAndCrossvalid.R
R/BiomodModel.R
R/Crossvalidate.R
R/GBM.R
R/LogisticRegression.R
R/MESSMask.R
R/MachineLearn.R
R/MaxEnt.R
R/MaxLike.R
R/MyMaxLike.R
R/NaiveRandomPresence.R
R/NaiveRandomPresenceAbsence.R
R/NoProcess.R
R/OneHundredBackground.R
R/OneThousandBackground.R
R/OptGRaF.R
R/QuickGRaF.R
R/RandomForest.R
R/StandardiseCov.R
R/StochasticLogisticRegression.R
R/Transform.R
R/addInteraction.R
R/mgcv.R
man/LocalOccurrenceData.Rd
man/NaiveRandomPresence.Rd
man/NaiveRandomPresenceAbsence.Rd
man/NaiveRandomRaster.Rd

This is going to be useful in testing

Add possiblity to set your own CRS in some modules

---

R/Appify.R
R/MESSMask.R
R/PrintMap.R

Module fixes and improvements

---

R/PrintMap.R
man/PrintMap.Rd

Add a number of different methods for determining thresholds in PrintMap.

Different threshold methods for PrintMap

---

R/Domain.R

also pushed through to fix testing

make Domain ignore non-presence data

---

R/Domain.R

also pushed through to fix testing

stop Domain from dropping dimensions

---

R/ResponsePlot.R

Add if statements to response plot to handle numeric or character vector input for covariate selection

modify ResponsePlot to handle vector input

---

R/ResponsePlot.R
man/ResponsePlot.Rd

Also added additional comments

remove par setting reset to allow users to set layout

---

R/InteractiveOccurrenceMap.R
man/InteractiveOccurrenceMap.Rd

Now plots the data points and the raster layers from the dataset.

Updated InteractiveOccurrenceMap.

---

R/Background.R
man/Background.Rd

fixes [this issue](https://github.com/zoonproject/zoon/issues/388)

bug fix biaslayer naming conflict Background()

---

R/CovHistograms.R

improve spacing around plots, and modify for odd number of covariates

---

R/malariaAtlas_PR.R

Fix error in previous PR for malariaAtlas modules.

Fix extent arg in malariaAtlas_PR.

---

R/malariaAtlas_VecOcc.R

Test are failing here and on master. I'm afraid I haven't had time to work it out.

New mosquito module
